"""Short names for Luxtronik fault numbers. Add a code by appending one line to FAULTS."""

FAULTS = (
    (701, "Low pressure fault"),
    (702, "Low pressure block"),
    (703, "Frost protection"),
    (704, "Hot gas fault"),
    (705, "Motor protection fan"),
    (706, "Motor protection BSUP"),
    (707, "Coding HP"),
    (708, "Sensor return"),
    (709, "Sensor flow"),
    (710, "Sensor hot gas"),
    (711, "Sensor outdoor temp."),
    (712, "Sensor domestic hot water"),
    (713, "Sensor heat source inlet"),
    (714, "Hot gas DHW"),
    (715, "High pressure shutdown"),
    (716, "High pressure fault"),
    (717, "Flow rate heat source"),
    (718, "Max. outdoor temp."),
    (719, "Min. outdoor temp."),
    (720, "Heat source temperature"),
    (721, "Low pressure shutdown"),
    (722, "Temp. diff. heating water"),
    (723, "Temp. diff. DHW"),
    (724, "Temp. diff. defrost"),
    (725, "System fault DHW"),
    (726, "Sensor mixing circuit 1"),
    (727, "Brine pressure"),
    (728, "Sensor heat source outlet"),
    (729, "Phase rotation fault"),
    (730, "Screed drying output"),
    (732, "Cooling fault"),
    (733, "Anode fault"),
    (734, "Anode fault"),
    (735, "Sensor ext. energy"),
    (736, "Sensor solar collector"),
    (737, "Sensor solar storage"),
    (738, "Sensor mixing circuit 2"),
    (750, "Sensor return external"),
    (751, "Phase monitoring fault"),
    (752, "Phase monitor / flow fault"),
    (755, "Connection to slave lost"),
    (756, "Connection to master lost"),
    (757, "Low pressure fault on DHW unit"),
    (758, "Defrost fault"),
    (759, "TDI message"),
    (760, "Defrost fault"),
    (761, "LIN timeout"),
    (762, "Sensor fault compressor intake"),
    (763, "Sensor fault evaporator intake"),
    (764, "Sensor fault crankcase heater"),
    (765, "Overheating"),
    (766, "Operating limit compressor"),
    (767, "STB electric heater"),
    (770, "Low superheat"),
    (771, "High superheat"),
    (776, "Operating limit compressor"),
    (777, "Expansion valve defective"),
    (778, "Sensor low pressure"),
    (779, "Sensor high pressure"),
    (780, "Sensor EVI"),
    (781, "Sensor liquid before expansion valve"),
    (782, "Sensor EVI suction gas"),
    (783, "Communication SEC - inverter"),
    (784, "VSS blocked"),
    (785, "SEC board defective"),
    (786, "Communication SEC - inverter"),
    (787, "Compressor alarm"),
    (788, "Severe inverter error"),
    (789, "Severe inverter error"),
    (790, "Severe inverter error"),
    (791, "ModBus connection lost"),
    (792, "LIN connection broken"),
    (793, "Severe inverter error"),
)

_BY_CODE = {code: name for code, name in FAULTS}


def fault_name(code) -> str | None:
    """Return the short name for a fault number, or None when it is not listed."""
    try:
        number = int(code)
    except (TypeError, ValueError):
        return None
    return _BY_CODE.get(number)
